/*Config
    RetornaLista
    Retorno
        -ComprovanteRendimentosEntidade
    Parametros
        -CD_PESSOA:int
        -ANO_CALENDARIO:string
*/

SELECT CR.SQ_DECLARACAO,
       CR.VL_DECLARACAO,
       CC.VL_DECLARACAO AS VL_COMPLEMENTAR,
       EX.ANO_CALENDARIO,
       EX.ANO_EXERCICIO,
       CO.CD_RECEITA,
       CO.DS_RECEITA,
       ID.NR_ITEM_DECLARACAO,
       ID.DS_ITEM_DECLARACAO,
       ID.NR_POSICAO_COLUNA
FROM FI_COMPROVANTE_RENDIMENTOS CR
    INNER JOIN FI_EXERCICIO_TRIBUTO EX ON EX.SQ_EXERCICIO = CR.SQ_EXERCICIO
    INNER JOIN FI_ITEM_DECLARACAO ID ON ID.SQ_ITEM_DECLARACAO = CR.SQ_ITEM_DECLARACAO
    INNER JOIN FI_CODIGO_RECEITA CO ON CO.SQ_CODIGO = CR.SQ_CODIGO
    LEFT OUTER JOIN FI_COMPROVANTE_COMPLEMENTAR CC ON CC.SQ_DECLARACAO = CR.SQ_DECLARACAO
    LEFT OUTER JOIN FI_PESSOA PE ON PE.CD_PESSOA = CC.CD_PESSOA
    LEFT OUTER JOIN FI_PESSOA_FISICA PF ON PF.CD_PESSOA = CC.CD_PESSOA
WHERE CR.CD_PESSOA = @CD_PESSOA
  AND EX.ANO_CALENDARIO = @ANO_CALENDARIO
ORDER BY ID.NR_ITEM_DECLARACAO