/*Config
    RetornaLista
    Retorno
        -PessoaFisicaEntidade
    Parametros
        -CPF:string
*/

SELECT FI_PESSOA_FISICA.*,
	FI_PESSOA.NO_PESSOA
FROM FI_PESSOA_FISICA
INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = FI_PESSOA_FISICA.CD_PESSOA
INNER JOIN FI_CONTRATO_TRABALHO AS CONTRATO ON CONTRATO.CD_PESSOA = FI_PESSOA.CD_PESSOA
WHERE FI_PESSOA_FISICA.NR_CPF = @CPF