/*Config
    Retorno
        -FichaSalarioContribuicaoEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
        -SQ_PLANO_PREVIDENCIAL:int
*/

SELECT TOP(1) * 
FROM FI_FICHA_SALARIO_CONTRIBUICAO
WHERE SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
ORDER BY DT_REFERENCIA DESC