/*Config
    RetornaLista
    Retorno
        -ProcessoBeneficioEntidade
    Parametros
        -CD_PESSOA:int
*/

SELECT * FROM FI_PROCESSO_BENEFICIO
INNER JOIN FI_RECEBEDOR_BENEFICIO ON FI_RECEBEDOR_BENEFICIO.SQ_PROCESSO = FI_PROCESSO_BENEFICIO.SQ_PROCESSO
WHERE FI_RECEBEDOR_BENEFICIO.CD_PESSOA_RECEB = @CD_PESSOA