/*Config
    RetornaLista
    Retorno
        -FichaContribPrevidencialEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
        -SQ_PLANO_PREVIDENCIAL:int
*/

SELECT 
	FI_FICHA_CONTRIB_PREVIDENCIAL.*,
    FI_FUNDO_CONTRIBUICAO.DS_TIPO_FUNDO,
	FI_TIPO_COBRANCA.DS_TIPO_COBRANCA
FROM FI_FICHA_CONTRIB_PREVIDENCIAL 
INNER JOIN FI_FUNDO_CONTRIBUICAO ON FI_FUNDO_CONTRIBUICAO.SQ_TIPO_FUNDO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_FUNDO
INNER JOIN FI_TIPO_COBRANCA ON FI_TIPO_COBRANCA.SQ_TIPO_COBRANCA = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_COBRANCA
WHERE FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
  AND FI_FICHA_CONTRIB_PREVIDENCIAL.DT_COMPETENCIA = (SELECT MAX(DT_COMPETENCIA)
													    FROM FI_FICHA_CONTRIB_PREVIDENCIAL FF2
													   WHERE FF2.SQ_PLANO_PREVIDENCIAL = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL
														 AND FF2.SQ_CONTRATO_TRABALHO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO)
ORDER BY FI_FICHA_CONTRIB_PREVIDENCIAL.DT_COMPETENCIA,
       FI_FUNDO_CONTRIBUICAO.DS_TIPO_FUNDO,
       FI_TIPO_COBRANCA.DS_TIPO_COBRANCA