/*Config
    RetornaLista
    Retorno
        -FichaContribPrevidencialEntidade
    Parametros
        -SQ_PLANO_PREVIDENCIAL:int
        -SQ_CONTRATO_TRABALHO:int
        -NATUREZA:string
        -DT_INICIAL:DateTime
        -DT_FINAL:DateTime
*/

SELECT CO.DT_REFERENCIA,
       CO.DT_COMPETENCIA,
       CO.DT_APORTE,
       FC.DS_TIPO_FUNDO,
       TC.DS_TIPO_COBRANCA,
       CO.IR_OPERACAO,
       CO.VL_CONTRIBUICAO,
       CO.QT_COTA_CONTRIBUICAO,
       CO.VL_COTA,
       TC.IC_NATUREZA_COBRANCA,
       CO.SQ_PLANO_PREVIDENCIAL,
       co.*
  FROM fi_ficha_contrib_previdencial CO
       INNER JOIN fi_tipo_cobranca TC ON TC.SQ_TIPO_COBRANCA = CO.SQ_TIPO_COBRANCA
       INNER JOIN fi_fundo_contribuicao FC ON FC.SQ_TIPO_FUNDO = CO.SQ_TIPO_FUNDO AND FC.SQ_PLANO_PREVIDENCIAL = CO.SQ_PLANO_PREVIDENCIAL 
WHERE CO.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
  AND CO.SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND TC.IC_NATUREZA_COBRANCA = @NATUREZA
  AND CO.DT_REFERENCIA >= @DT_INICIAL
  AND CO.DT_REFERENCIA <= @DT_FINAL
ORDER BY CO.DT_REFERENCIA, TC.DS_TIPO_COBRANCA, CO.DT_APORTE