/*Config
    Retorno
        -DateTime
    Parametros
        -SQ_CONTRATO_TRABALHO:int
        -SQ_PLANO_PREVIDENCIAL:int
*/

SELECT MIN(DT_REFERENCIA) 
FROM FI_FICHA_CONTRIB_PREVIDENCIAL 
WHERE SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO 
AND SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL