/*Config
    RetornaLista
    Retorno
        -DependenteEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
*/

SELECT 
	FI_PESSOA.NO_PESSOA,
	FI_PESSOA_FISICA.NR_CPF,
	FI_PESSOA_FISICA.DT_NASCIMENTO,
	FI_GRAU_PARENTESCO.DS_GRAU_PARENTESCO,
	FI_DEPENDENTE.*
FROM FI_DEPENDENTE
    INNER JOIN FI_CONTRATO_TRABALHO ON FI_CONTRATO_TRABALHO.CD_PESSOA = FI_DEPENDENTE.CD_PESSOA_PAI
    INNER JOIN FI_PESSOA_FISICA ON FI_PESSOA_FISICA.CD_PESSOA = FI_DEPENDENTE.CD_PESSOA_DEP
	INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = FI_DEPENDENTE.CD_PESSOA_DEP
	INNER JOIN FI_GRAU_PARENTESCO ON FI_GRAU_PARENTESCO.CD_GRAU_PARENTESCO = FI_DEPENDENTE.CD_GRAU_PARENTESCO
WHERE (FI_CONTRATO_TRABALHO.SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO)