/*Config
    Retorno
        -void
    Parametros
        -USR_CODIGO:int
        -USR_LOGIN:string
        -USR_SENHA:string
        -USR_ADMINISTRADOR:string
        -USR_TIPO_EXPIRACAO:string
        -USR_NOME:string
        -USR_EMAIL:string
        -CD_PESSOA:int
        -EE_TERMO_RESPONSABILIDADE:string
        -CD_PESSOA_CLIENTE:int
*/

UPDATE FR_USUARIO 
SET USR_CODIGO = @USR_CODIGO,
    USR_LOGIN = @USR_LOGIN,
    USR_SENHA = @USR_SENHA,
    USR_ADMINISTRADOR = @USR_ADMINISTRADOR,
    USR_TIPO_EXPIRACAO = @USR_TIPO_EXPIRACAO,
    USR_NOME = @USR_NOME,
    USR_EMAIL = @USR_EMAIL,
    CD_PESSOA = @CD_PESSOA,
    EE_TERMO_RESPONSABILIDADE = @EE_TERMO_RESPONSABILIDADE,
    CD_PESSOA_CLIENTE = @CD_PESSOA_CLIENTE
WHERE USR_CODIGO = @USR_CODIGO