/*Config
    Retorno
        -void
    Parametros
        -USR_CODIGO:int
        -USR_LOGIN:string
        -USR_SENHA:string
        -USR_ADMINISTRADOR:string
        -USR_TIPO_EXPIRACAO:string
        -USR_NOME:string
        -USR_EMAIL:string
        -CD_PESSOA:int
        -EE_TERMO_RESPONSABILIDADE:string
        -CD_PESSOA_CLIENTE:int
*/

INSERT INTO FR_USUARIO(USR_CODIGO, USR_LOGIN, USR_SENHA, USR_ADMINISTRADOR, USR_TIPO_EXPIRACAO, USR_NOME, USR_EMAIL, CD_PESSOA, EE_TERMO_RESPONSABILIDADE, CD_PESSOA_CLIENTE)
VALUES (@USR_CODIGO, @USR_LOGIN, @USR_SENHA, @USR_ADMINISTRADOR, @USR_TIPO_EXPIRACAO, @USR_NOME, @USR_EMAIL, @CD_PESSOA, @EE_TERMO_RESPONSABILIDADE, @CD_PESSOA_CLIENTE)