INSERT INTO FR_USUARIO (
USR_CODIGO,
USR_LOGIN,            
USR_SENHA,                                                        
USR_ADMINISTRADOR,
USR_TIPO_EXPIRACAO, 
USR_DIAS_EXPIRACAO,
USR_IMAGEM_DIGITAL,
USR_FOTO,
USR_NOME,
USR_EMAIL,
USR_DIGITAL,
USR_INICIO_EXPIRACAO,
CD_PESSOA,
EE_TERMO_RESPONSABILIDADE ,
USR_SENHA_NOVA,
CD_PESSOA_CLIENTE,
NO_SENHA) 
(SELECT 257 + FI_PESSOA_FISICA.CD_PESSOA,
	fi_pessoa_fisica.NR_CPF,
	'ASD' AS USR_SENHA,
	'N' AS ADM,
	'N' AS TIPO_EXP,
	NULL AS DIAS_EXP,
	NULL AS IMAGEM,
	NULL AS FOTO,
	FI_PESSOA.NO_PESSOA,
	fi_endereco_pessoa.NO_EMAIL,
	NULL,
	NULL,
	FI_PESSOA.CD_PESSOA,
	'S',
	NULL,
	1,
	NULL
FROM FI_PESSOA_FISICA
INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = fi_pessoa_fisica.CD_PESSOA
LEFT JOIN FI_ENDERECO_PESSOA ON FI_ENDERECO_PESSOA.CD_PESSOA = FI_PESSOA.CD_PESSOA
WHERE NR_CPF IS NOT NULL)