CREATE TABLE [dbo].[TBG_ARQUIVO_UPLOAD](
	[OID_ARQUIVO_UPLOAD] [numeric](10, 0) IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NOM_ARQUIVO_ORIGINAL] [varchar](4000) NOT NULL,
	[NOM_EXT_ARQUIVO] [varchar](10) NULL,
	[DTA_UPLOAD] [datetime] NOT NULL,
	[NOM_DIRETORIO_LOCAL] [varchar](200) NOT NULL,
	[NOM_ARQUIVO_LOCAL] [varchar](4000) NOT NULL,
	[OID_USUARIO] [numeric](10, 0) NULL,
	[OID_SERVICO] [numeric](10, 0) NULL,
	[OID_MODULO] [numeric](10, 0) NULL,
	[OID_SISTEMA] [numeric](10, 0) NULL,
	[IND_STATUS] [numeric](5, 0) NOT NULL,
 CONSTRAINT [TBG_ARQUIVO_UPLOAD_PK] PRIMARY KEY NONCLUSTERED 
(
	[OID_ARQUIVO_UPLOAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBG_ARQUIVO_UPLOAD] ADD  DEFAULT ((1)) FOR [IND_STATUS]
GO

ALTER TABLE [dbo].[TBG_ARQUIVO_UPLOAD]  WITH CHECK ADD  CONSTRAINT [CKC_IND_STATUS_TB234234] CHECK  (([IND_STATUS]=(3) OR [IND_STATUS]=(2) OR [IND_STATUS]=(1)))
GO

ALTER TABLE [dbo].[TBG_ARQUIVO_UPLOAD] CHECK CONSTRAINT [CKC_IND_STATUS_TB234234]
GO


