CREATE TABLE [dbo].[WEB_DOCUMENTO](
	[OID_DOCUMENTO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[OID_ARQUIVO_UPLOAD] [numeric](10, 0) NOT NULL,
	[TXT_TITULO] [varchar](1000) NOT NULL,
	[IND_ATIVO] [varchar](3) NOT NULL,
	[NUM_ORDEM] [numeric](10, 0) NOT NULL,
	[OID_DOCUMENTO_PASTA] [numeric](10, 0) NULL,
 CONSTRAINT [WEB_DOCUMENTO_PK] PRIMARY KEY CLUSTERED 
(
	[OID_DOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [WEB_DOCUMENTO_FK01] FOREIGN KEY([OID_ARQUIVO_UPLOAD])
REFERENCES [dbo].[TBG_ARQUIVO_UPLOAD] ([OID_ARQUIVO_UPLOAD])
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO] CHECK CONSTRAINT [WEB_DOCUMENTO_FK01]
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [WEB_DOCUMENTO_FK02] FOREIGN KEY([OID_DOCUMENTO_PASTA])
REFERENCES [dbo].[WEB_DOCUMENTO_PASTA] ([OID_DOCUMENTO_PASTA])
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO] CHECK CONSTRAINT [WEB_DOCUMENTO_FK02]
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [CKC_IND_ATIVO_WEB_DOCU] CHECK  ((([IND_ATIVO]='NAO' OR [IND_ATIVO]='SIM') AND [IND_ATIVO]=upper([IND_ATIVO])))
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO] CHECK CONSTRAINT [CKC_IND_ATIVO_WEB_DOCU]
GO


