CREATE TABLE [dbo].[WEB_DOCUMENTO_PASTA](
	[OID_DOCUMENTO_PASTA] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[NOM_PASTA] [varchar](50) NOT NULL,
	[OID_DOCUMENTO_PASTA_PAI] [numeric](10, 0) NULL,
 CONSTRAINT [PK_WEB_DOCUMENTO_PASTA] PRIMARY KEY CLUSTERED 
(
	[OID_DOCUMENTO_PASTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO_PASTA]  WITH CHECK ADD  CONSTRAINT [WEB_DOCUMENTO_PASTA_FK01] FOREIGN KEY([OID_DOCUMENTO_PASTA])
REFERENCES [dbo].[WEB_DOCUMENTO_PASTA] ([OID_DOCUMENTO_PASTA])
GO

ALTER TABLE [dbo].[WEB_DOCUMENTO_PASTA] CHECK CONSTRAINT [WEB_DOCUMENTO_PASTA_FK01]
GO


