/*Config
    RetornaLista
    Retorno
        -DocumentoEntidade
    Parametros
        -SQ_PLANO_PREVIDENCIAL:int
        -OID_DOCUMENTO_PASTA:decimal?
*/

SELECT WEB_DOCUMENTO.*
FROM WEB_DOCUMENTO
WHERE OID_DOCUMENTO NOT IN (SELECT OID_DOCUMENTO FROM  WEB_DOCUMENTO_PLANO WHERE SQ_PLANO_PREVIDENCIAL <> @SQ_PLANO_PREVIDENCIAL)
  AND ((OID_DOCUMENTO_PASTA = @OID_DOCUMENTO_PASTA)
   OR (@OID_DOCUMENTO_PASTA IS NULL AND OID_DOCUMENTO_PASTA IS NULL))