/*Config
    Retorno
        -DadosPessoaisEntidade
    Parametros
        -CD_PESSOA:int
*/

SELECT FI_PESSOA.NO_PESSOA, 
       FI_PESSOA_FISICA.IR_SEXO, 
       FI_PESSOA_FISICA.DT_NASCIMENTO, 
       FI_PESSOA_FISICA.NR_CPF, 
       FI_PESSOA.CD_PESSOA, 
       CASE 
         WHEN FI_PESSOA_FISICA.IR_SEXO = 'M' THEN 'MASCULINO' 
         WHEN FI_PESSOA_FISICA.IR_SEXO = 'F' THEN 'FEMININO' 
       END AS DS_SEXO, 
       ENDERECO.NR_CEP, 
       ENDERECO.DS_ENDERECO, 
       ENDERECO.NR_ENDERECO, 
       ENDERECO.DS_COMPLEMENTO, 
       ENDERECO.NO_BAIRRO, 
       ENDERECO.NR_FONE, 
       ENDERECO.NR_CELULAR, 
       ENDERECO.NO_EMAIL 
FROM   FR_USUARIO A 
INNER JOIN FR_USUARIO_GRUPO B ON B.USR_CODIGO = A.USR_CODIGO 
INNER JOIN FR_GRUPO C ON C.GRP_CODIGO = B.GRP_CODIGO 
INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = A.CD_PESSOA 
INNER JOIN FI_PESSOA_FISICA ON FI_PESSOA_FISICA.CD_PESSOA = A.CD_PESSOA 
INNER JOIN FI_ENDERECO_PESSOA AS ENDERECO ON ENDERECO.CD_PESSOA = A.CD_PESSOA 
WHERE IC_CATEG_USUARIO = 'PE' 
  AND FI_PESSOA.CD_PESSOA = @CD_PESSOA