/*Config
    Retorno
        -DadosPessoaisEntidade
    Parametros
        -CD_PESSOA:int
*/

SELECT 
    CONTRATO.SQ_CONTRATO_TRABALHO, 
    CONTRATO.NR_REGISTRO, 
    CONTRATO.DT_ADMISSAO, 
    CONTRATO.DT_DEMISSAO, 
    FI_PESSOA.NO_PESSOA, 
    FI_PESSOA_FISICA.IR_SEXO, 
    FI_PESSOA_FISICA.DT_NASCIMENTO, 
    FI_PESSOA_FISICA.NR_CPF,
    FI_PESSOA.CD_PESSOA,
    EMPRESA.NO_SIGLA AS SIGLA_EMPRESA,
	CASE
		WHEN FI_PESSOA_FISICA.IR_SEXO = 'M' THEN 'MASCULINO'
		WHEN FI_PESSOA_FISICA.IR_SEXO = 'F' THEN 'FEMININO'
	END AS DS_SEXO,
	ENDERECO.NR_CEP,
	ENDERECO.DS_ENDERECO,
	ENDERECO.NR_ENDERECO,
	ENDERECO.DS_COMPLEMENTO,
	ENDERECO.NO_BAIRRO,
	ENDERECO.NR_FONE,
	ENDERECO.NR_CELULAR,
	ENDERECO.NO_EMAIL
FROM FI_CONTRATO_TRABALHO AS CONTRATO
INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = CONTRATO.CD_PESSOA
INNER JOIN FI_PESSOA_FISICA ON FI_PESSOA_FISICA.CD_PESSOA = CONTRATO.CD_PESSOA
INNER JOIN FI_PESSOA AS EMPRESA ON EMPRESA.CD_PESSOA = CONTRATO.CD_PESSOA_PATR
INNER JOIN FI_ENDERECO_PESSOA AS ENDERECO ON ENDERECO.CD_PESSOA = CONTRATO.CD_PESSOA
WHERE FI_PESSOA.CD_PESSOA = @CD_PESSOA